import type { NextPage } from "next";
import { handleClick, getSearchElements } from "../helpers/functions";
import Head from "next/head";
import { Fragment } from "react";

const Home: NextPage = () => {
  
  return (
    <Fragment>
      <Head>
        <title>Create A Hidden Search</title>
        <meta
          name="description"
          content="A Hidden search bar generated by create next app"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossOrigin="anonymous"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Create A Hidden Search Bar</h1>
        <div className="search">
          <input type="text" placeholder="Search..." />
          <button onClick={handleClick}>
            <i className="fas fa-search"></i>
          </button>
        </div>
      </main>
    </Fragment>
  );
};

export default Home;
